import '../../../../core/colors/app_colors.dart';
import '../../../../shared/models/schedule_models.dart';
import '../../models/section_management_models.dart';

DateTime _dateOnly(DateTime date) => DateTime(date.year, date.month, date.day);

DateTime _startOfWeek(DateTime date) {
  final normalized = _dateOnly(date);
  return normalized.subtract(Duration(days: normalized.weekday - 1));
}

SectionStudentRecord _student({
  required String id,
  required String name,
  required String email,
  required String status,
  required String department,
  required String yearLabel,
  required String currentSectionCode,
  required double gpa,
  required double attendanceRate,
  required int creditHours,
  required String performanceLabel,
  required String lastActivityLabel,
}) {
  return SectionStudentRecord(
    id: id,
    name: name,
    email: email,
    status: status,
    department: department,
    yearLabel: yearLabel,
    currentSectionCode: currentSectionCode,
    gpa: gpa,
    attendanceRate: attendanceRate,
    creditHours: creditHours,
    performanceLabel: performanceLabel,
    lastActivityLabel: lastActivityLabel,
  );
}

SectionSubjectRecord _subject({
  required String code,
  required String title,
  required int lecturesCount,
  required String instructorName,
  required String deliveryLabel,
  required String status,
  required double completionRate,
}) {
  return SectionSubjectRecord(
    code: code,
    title: title,
    lecturesCount: lecturesCount,
    instructorName: instructorName,
    deliveryLabel: deliveryLabel,
    status: status,
    completionRate: completionRate,
  );
}

SectionStaffRecord _staff({
  required String id,
  required String name,
  required String role,
  required String status,
  required String focusArea,
  required String officeHoursLabel,
  required double loadRate,
}) {
  return SectionStaffRecord(
    id: id,
    name: name,
    role: role,
    status: status,
    focusArea: focusArea,
    officeHoursLabel: officeHoursLabel,
    loadRate: loadRate,
  );
}

List<ScheduleEventModel> _buildScheduleEvents(DateTime weekStart, String code) {
  return [
    ScheduleEventModel(
      id: '$code-ev-1',
      title: 'Lecture 08',
      course: 'Object-Oriented Programming',
      instructor: 'Dr. Hadeer Salah',
      location: 'Hall B12',
      type: 'lecture',
      status: 'planned',
      start: weekStart.add(const Duration(hours: 9)),
      end: weekStart.add(const Duration(hours: 11)),
      color: AppColors.primary,
    ),
    ScheduleEventModel(
      id: '$code-ev-2',
      title: 'Section Lab',
      course: 'Data Structures',
      instructor: 'Eng. Ahmed Samir',
      location: 'Lab C3',
      type: 'section',
      status: 'planned',
      start: weekStart.add(const Duration(hours: 12)),
      end: weekStart.add(const Duration(hours: 14)),
      color: AppColors.secondary,
    ),
    ScheduleEventModel(
      id: '$code-ev-3',
      title: 'Quiz 02',
      course: 'Discrete Mathematics',
      instructor: 'Dr. Mostafa Nader',
      location: 'Quiz Hall 1',
      type: 'quiz',
      status: 'planned',
      start: weekStart.add(const Duration(days: 2, hours: 10)),
      end: weekStart.add(const Duration(days: 2, hours: 11)),
      color: AppColors.warning,
    ),
    ScheduleEventModel(
      id: '$code-ev-4',
      title: 'Midterm Review',
      course: 'Computer Architecture',
      instructor: 'Dr. Reem Fawzy',
      location: 'Studio A',
      type: 'section',
      status: 'planned',
      start: weekStart.add(const Duration(days: 3, hours: 11)),
      end: weekStart.add(const Duration(days: 3, hours: 13)),
      color: AppColors.secondary,
    ),
    ScheduleEventModel(
      id: '$code-ev-5',
      title: 'Midterm Exam',
      course: 'Object-Oriented Programming',
      instructor: 'Dr. Hadeer Salah',
      location: 'Main Auditorium',
      type: 'exam',
      status: 'planned',
      start: weekStart.add(const Duration(days: 4, hours: 9)),
      end: weekStart.add(const Duration(days: 4, hours: 11)),
      color: AppColors.danger,
    ),
  ];
}

List<SectionManagementRecord> buildMockSections() {
  final weekStart = _startOfWeek(DateTime.now());
  final primarySubjects = [
    _subject(
      code: 'CS221',
      title: 'Object-Oriented Programming',
      lecturesCount: 14,
      instructorName: 'Dr. Hadeer Salah',
      deliveryLabel: 'Lecture + Lab',
      status: 'Active',
      completionRate: 0.82,
    ),
    _subject(
      code: 'CS223',
      title: 'Data Structures',
      lecturesCount: 12,
      instructorName: 'Dr. Salma Adel',
      deliveryLabel: 'Lecture + Section',
      status: 'Active',
      completionRate: 0.76,
    ),
    _subject(
      code: 'CS225',
      title: 'Discrete Mathematics',
      lecturesCount: 10,
      instructorName: 'Dr. Mostafa Nader',
      deliveryLabel: 'Lecture',
      status: 'Planned',
      completionRate: 0.65,
    ),
    _subject(
      code: 'CS227',
      title: 'Computer Architecture',
      lecturesCount: 11,
      instructorName: 'Dr. Reem Fawzy',
      deliveryLabel: 'Lecture + Lab',
      status: 'Active',
      completionRate: 0.71,
    ),
    _subject(
      code: 'CS229',
      title: 'Technical Writing',
      lecturesCount: 8,
      instructorName: 'Eng. Menna Wael',
      deliveryLabel: 'Workshop',
      status: 'Active',
      completionRate: 0.88,
    ),
  ];

  final primaryStaff = [
    _staff(
      id: 'stf-1',
      name: 'Dr. Hadeer Salah',
      role: 'Doctor',
      status: 'Active',
      focusArea: 'Programming foundations',
      officeHoursLabel: 'Sun & Tue • 11:00',
      loadRate: 0.74,
    ),
    _staff(
      id: 'stf-2',
      name: 'Dr. Salma Adel',
      role: 'Doctor',
      status: 'Active',
      focusArea: 'Algorithms and data structures',
      officeHoursLabel: 'Mon • 12:30',
      loadRate: 0.82,
    ),
    _staff(
      id: 'stf-3',
      name: 'Dr. Mostafa Nader',
      role: 'Doctor',
      status: 'Active',
      focusArea: 'Discrete systems',
      officeHoursLabel: 'Wed • 13:00',
      loadRate: 0.58,
    ),
    _staff(
      id: 'stf-4',
      name: 'Eng. Ahmed Samir',
      role: 'Assistant',
      status: 'Active',
      focusArea: 'Lab supervision',
      officeHoursLabel: 'Daily • 10:00',
      loadRate: 0.63,
    ),
    _staff(
      id: 'stf-5',
      name: 'Eng. Menna Wael',
      role: 'Assistant',
      status: 'Active',
      focusArea: 'Assessment operations',
      officeHoursLabel: 'Tue & Thu • 14:00',
      loadRate: 0.67,
    ),
    _staff(
      id: 'stf-6',
      name: 'Eng. Nourhan Essam',
      role: 'Assistant',
      status: 'Inactive',
      focusArea: 'Lab contingency coverage',
      officeHoursLabel: 'On-demand',
      loadRate: 0.28,
    ),
  ];

  final sectionAStudents = [
    _student(
      id: 'ST-2101',
      name: 'Mariam Tarek',
      email: 'mariam.tarek@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.86,
      attendanceRate: 0.95,
      creditHours: 17,
      performanceLabel: 'Excellent',
      lastActivityLabel: '13 min ago',
    ),
    _student(
      id: 'ST-2102',
      name: 'Omar Adel',
      email: 'omar.adel@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.72,
      attendanceRate: 0.91,
      creditHours: 17,
      performanceLabel: 'Strong',
      lastActivityLabel: '28 min ago',
    ),
    _student(
      id: 'ST-2103',
      name: 'Youssef Ali',
      email: 'youssef.ali@tolab.edu',
      status: 'Inactive',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 2.41,
      attendanceRate: 0.68,
      creditHours: 14,
      performanceLabel: 'At risk',
      lastActivityLabel: 'Yesterday',
    ),
    _student(
      id: 'ST-2104',
      name: 'Sarah Emad',
      email: 'sarah.emad@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.49,
      attendanceRate: 0.88,
      creditHours: 16,
      performanceLabel: 'Healthy',
      lastActivityLabel: '1 h ago',
    ),
    _student(
      id: 'ST-2105',
      name: 'Karim Nabil',
      email: 'karim.nabil@tolab.edu',
      status: 'Active',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.11,
      attendanceRate: 0.84,
      creditHours: 15,
      performanceLabel: 'Stable',
      lastActivityLabel: '2 h ago',
    ),
    _student(
      id: 'ST-2106',
      name: 'Nada Gamal',
      email: 'nada.gamal@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.68,
      attendanceRate: 0.93,
      creditHours: 17,
      performanceLabel: 'Strong',
      lastActivityLabel: '3 h ago',
    ),
    _student(
      id: 'ST-2107',
      name: 'Mohamed Ashraf',
      email: 'mohamed.ashraf@tolab.edu',
      status: 'Active',
      department: 'Data Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 2.88,
      attendanceRate: 0.79,
      creditHours: 15,
      performanceLabel: 'Monitor',
      lastActivityLabel: 'Today',
    ),
    _student(
      id: 'ST-2108',
      name: 'Habiba Essam',
      email: 'habiba.essam@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.95,
      attendanceRate: 0.97,
      creditHours: 18,
      performanceLabel: 'Excellent',
      lastActivityLabel: '35 min ago',
    ),
    _student(
      id: 'ST-2109',
      name: 'Ali Hossam',
      email: 'ali.hossam@tolab.edu',
      status: 'Active',
      department: 'Information Systems',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.19,
      attendanceRate: 0.81,
      creditHours: 16,
      performanceLabel: 'Stable',
      lastActivityLabel: '4 h ago',
    ),
    _student(
      id: 'ST-2110',
      name: 'Menna Taha',
      email: 'menna.taha@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-A',
      gpa: 3.58,
      attendanceRate: 0.90,
      creditHours: 17,
      performanceLabel: 'Healthy',
      lastActivityLabel: '15 min ago',
    ),
  ];

  final sectionBStudents = [
    ...sectionAStudents
        .take(6)
        .map((student) => student.copyWith(currentSectionCode: 'CS-Y2-B')),
    _student(
      id: 'ST-2201',
      name: 'Lina Ahmed',
      email: 'lina.ahmed@tolab.edu',
      status: 'Active',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-B',
      gpa: 3.44,
      attendanceRate: 0.89,
      creditHours: 17,
      performanceLabel: 'Healthy',
      lastActivityLabel: '45 min ago',
    ),
    _student(
      id: 'ST-2202',
      name: 'Adam Saeed',
      email: 'adam.saeed@tolab.edu',
      status: 'Active',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'CS-Y2-B',
      gpa: 3.07,
      attendanceRate: 0.82,
      creditHours: 15,
      performanceLabel: 'Stable',
      lastActivityLabel: 'Today',
    ),
  ];

  final aiStudents = [
    _student(
      id: 'ST-2301',
      name: 'Reem Fawzy',
      email: 'reem.fawzy@tolab.edu',
      status: 'Active',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'AI-Y2-A',
      gpa: 3.76,
      attendanceRate: 0.93,
      creditHours: 18,
      performanceLabel: 'Strong',
      lastActivityLabel: '20 min ago',
    ),
    _student(
      id: 'ST-2302',
      name: 'Hassan Wael',
      email: 'hassan.wael@tolab.edu',
      status: 'Active',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'AI-Y2-A',
      gpa: 3.34,
      attendanceRate: 0.85,
      creditHours: 16,
      performanceLabel: 'Healthy',
      lastActivityLabel: '1 h ago',
    ),
    _student(
      id: 'ST-2303',
      name: 'Farah Elsayed',
      email: 'farah.elsayed@tolab.edu',
      status: 'Inactive',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'AI-Y2-A',
      gpa: 2.57,
      attendanceRate: 0.74,
      creditHours: 13,
      performanceLabel: 'At risk',
      lastActivityLabel: '2 days ago',
    ),
    _student(
      id: 'ST-2304',
      name: 'Bassel Sherif',
      email: 'bassel.sherif@tolab.edu',
      status: 'Active',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      currentSectionCode: 'AI-Y2-A',
      gpa: 3.61,
      attendanceRate: 0.90,
      creditHours: 18,
      performanceLabel: 'Strong',
      lastActivityLabel: 'Today',
    ),
  ];

  return [
    SectionManagementRecord(
      id: 'sec-cs-y2-a',
      name: 'Software Engineering Cohort A',
      code: 'CS-Y2-A',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      yearValue: 2,
      semesterLabel: 'Spring 2026',
      status: 'Active',
      capacity: 96,
      description:
          'Premium operations view for a high-demand second-year section with blended teaching, tight seat control, and strong academic monitoring.',
      locationLabel: 'Innovation Building 4B',
      lastUpdatedLabel: 'Updated 14 min ago',
      students: sectionAStudents,
      subjects: primarySubjects,
      staff: primaryStaff,
      scheduleEvents: _buildScheduleEvents(weekStart, 'CS-Y2-A'),
      performanceTrend: const [
        SectionChartPoint(label: 'W1', value: 72),
        SectionChartPoint(label: 'W2', value: 74),
        SectionChartPoint(label: 'W3', value: 79),
        SectionChartPoint(label: 'W4', value: 81),
        SectionChartPoint(label: 'W5', value: 84),
        SectionChartPoint(label: 'W6', value: 86),
      ],
      alerts: const [
        SectionAlert(
          title: 'Attendance dip',
          message:
              'Three students dropped below the attendance threshold during the last seven days.',
          severity: 'warning',
        ),
        SectionAlert(
          title: 'Quiz window opens tomorrow',
          message:
              'Coordinate section assistants before the Thursday quiz goes live.',
          severity: 'info',
        ),
      ],
    ),
    SectionManagementRecord(
      id: 'sec-cs-y2-b',
      name: 'Software Engineering Cohort B',
      code: 'CS-Y2-B',
      department: 'Computer Science',
      yearLabel: 'Year 2',
      yearValue: 2,
      semesterLabel: 'Spring 2026',
      status: 'Active',
      capacity: 84,
      description:
          'Balanced sister section with healthier seat availability and lighter transfer pressure.',
      locationLabel: 'Innovation Building 3A',
      lastUpdatedLabel: 'Updated 22 min ago',
      students: sectionBStudents,
      subjects: primarySubjects.take(4).toList(),
      staff: primaryStaff.take(5).toList(),
      scheduleEvents: _buildScheduleEvents(weekStart, 'CS-Y2-B'),
      performanceTrend: const [
        SectionChartPoint(label: 'W1', value: 68),
        SectionChartPoint(label: 'W2', value: 70),
        SectionChartPoint(label: 'W3', value: 73),
        SectionChartPoint(label: 'W4', value: 75),
        SectionChartPoint(label: 'W5', value: 77),
        SectionChartPoint(label: 'W6', value: 80),
      ],
      alerts: const [
        SectionAlert(
          title: 'Transfer capacity available',
          message:
              'This cohort can absorb up to 10 students without crossing the warning threshold.',
          severity: 'info',
        ),
      ],
    ),
    SectionManagementRecord(
      id: 'sec-ai-y2-a',
      name: 'Applied AI Cohort A',
      code: 'AI-Y2-A',
      department: 'Artificial Intelligence',
      yearLabel: 'Year 2',
      yearValue: 2,
      semesterLabel: 'Spring 2026',
      status: 'Inactive',
      capacity: 42,
      description:
          'Smaller AI cohort used here to surface empty-section analytics and staff utilization decisions.',
      locationLabel: 'Digital Lab 2C',
      lastUpdatedLabel: 'Updated 1 h ago',
      students: aiStudents,
      subjects: primarySubjects.take(3).toList(),
      staff: primaryStaff.take(4).toList(),
      scheduleEvents: _buildScheduleEvents(weekStart, 'AI-Y2-A'),
      performanceTrend: const [
        SectionChartPoint(label: 'W1', value: 64),
        SectionChartPoint(label: 'W2', value: 62),
        SectionChartPoint(label: 'W3', value: 66),
        SectionChartPoint(label: 'W4', value: 69),
        SectionChartPoint(label: 'W5', value: 71),
        SectionChartPoint(label: 'W6', value: 70),
      ],
      alerts: const [
        SectionAlert(
          title: 'Low utilization',
          message:
              'Section occupancy is far below target. Consider merging or rebalancing staffing.',
          severity: 'warning',
        ),
      ],
    ),
  ];
}
