// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC47EPcE1muGpBLQGW56w8qVX3exq8TOEA',
    appId: '1:1023201199148:web:eafa989672b383671c3d89',
    messagingSenderId: '1023201199148',
    projectId: 'tolab-fci',
    authDomain: 'tolab-fci.firebaseapp.com',
    storageBucket: 'tolab-fci.firebasestorage.app',
    measurementId: 'G-JZ63PM4VRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv36_pKEvfOaDGzzXteZvwMUagZYDPa_Q',
    appId: '1:1023201199148:android:886cd34d3c86cf1d1c3d89',
    messagingSenderId: '1023201199148',
    projectId: 'tolab-fci',
    storageBucket: 'tolab-fci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIfAYziseqxZFLuHIJxj-1s78my-g0ss',
    appId: '1:1023201199148:ios:52a037936f4a09551c3d89',
    messagingSenderId: '1023201199148',
    projectId: 'tolab-fci',
    storageBucket: 'tolab-fci.firebasestorage.app',
    iosBundleId: 'com.example.tolabFci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIfAYziseqxZFLuHIJxj-1s78my-g0ss',
    appId: '1:1023201199148:ios:52a037936f4a09551c3d89',
    messagingSenderId: '1023201199148',
    projectId: 'tolab-fci',
    storageBucket: 'tolab-fci.firebasestorage.app',
    iosBundleId: 'com.example.tolabFci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC47EPcE1muGpBLQGW56w8qVX3exq8TOEA',
    appId: '1:1023201199148:web:f3c34adf68d1fbe31c3d89',
    messagingSenderId: '1023201199148',
    projectId: 'tolab-fci',
    authDomain: 'tolab-fci.firebaseapp.com',
    storageBucket: 'tolab-fci.firebasestorage.app',
    measurementId: 'G-3XJ17XD08P',
  );

}