import 'package:flutter/material.dart';

import '../../shared/models/academic_models.dart';
import '../../shared/models/auth_models.dart';
import '../../shared/models/content_models.dart';
import '../../shared/models/dashboard_models.dart';
import '../../shared/models/moderation_models.dart';
import '../../shared/models/notification_models.dart';
import '../../shared/models/schedule_models.dart';
import '../../shared/models/settings_models.dart';
import '../../shared/models/staff_member.dart';
import '../../shared/models/student.dart';
import '../../modules/subjects/models/subject_management_models.dart';
import '../../modules/staff/models/staff_admin_models.dart';
import '../colors/app_colors.dart';

class DemoDataService {
  const DemoDataService();

  UserProfile adminProfile() => const UserProfile(
    id: '1',
    name: 'Dr. Laila Hassan',
    email: 'admin@tolab.edu',
    role: 'super_admin',
    status: 'active',
    department: 'Engineering',
  );

  DashboardBundle dashboardBundle() => DashboardBundle(
    metrics: const [
      KpiMetric(
        label: 'Active students',
        value: '12,480',
        delta: '+8.4% vs last month',
        color: AppColors.primary,
        icon: Icons.school_rounded,
      ),
      KpiMetric(
        label: 'Academic staff',
        value: '684',
        delta: '+21 new assignments',
        color: AppColors.secondary,
        icon: Icons.groups_rounded,
      ),
      KpiMetric(
        label: 'Schedule events',
        value: '1,246',
        delta: '92 awaiting review',
        color: AppColors.purple,
        icon: Icons.calendar_month_rounded,
      ),
      KpiMetric(
        label: 'Moderation alerts',
        value: '18',
        delta: '-11 resolved today',
        color: AppColors.warning,
        icon: Icons.shield_moon_rounded,
      ),
    ],
    trends: const [
      TrendPoint('Jan', 420),
      TrendPoint('Feb', 510),
      TrendPoint('Mar', 560),
      TrendPoint('Apr', 610),
      TrendPoint('May', 700),
      TrendPoint('Jun', 820),
    ],
    distribution: const [
      DistributionSlice(label: 'Lectures', value: 42, color: AppColors.primary),
      DistributionSlice(
        label: 'Sections',
        value: 28,
        color: AppColors.secondary,
      ),
      DistributionSlice(label: 'Exams', value: 18, color: AppColors.warning),
      DistributionSlice(label: 'Tasks', value: 12, color: AppColors.purple),
    ],
    activities: const [
      ActivityItem(
        title: 'New staff assignment approved',
        subtitle: 'Computer Science / Data Structures',
        timestamp: '12 min ago',
        type: 'staff',
      ),
      ActivityItem(
        title: 'Bulk enrollment imported',
        subtitle: '312 students added to Spring 2026 offerings',
        timestamp: '48 min ago',
        type: 'enrollment',
      ),
      ActivityItem(
        title: 'Reported message removed',
        subtitle: 'Group: CS-4B collaborative channel',
        timestamp: '1h ago',
        type: 'moderation',
      ),
    ],
    alerts: const [
      '2 course offerings exceeded room capacity',
      '6 notification campaigns are queued for the evening',
      '4 uploaded files need manual virus review',
    ],
  );

  List<Student> students() => const [
    Student(
      id: 'ST-1001',
      name: 'Omar Adel',
      email: 'omar.adel@tolab.edu',
      department: 'Computer Science',
      level: 'Level 4',
      section: 'CS-4A',
      status: 'active',
      gpa: 3.72,
      enrolledSubjects: 6,
    ),
    Student(
      id: 'ST-1002',
      name: 'Mariam Tarek',
      email: 'mariam.tarek@tolab.edu',
      department: 'Information Systems',
      level: 'Level 3',
      section: 'IS-3B',
      status: 'active',
      gpa: 3.88,
      enrolledSubjects: 5,
    ),
    Student(
      id: 'ST-1003',
      name: 'Youssef Ali',
      email: 'youssef.ali@tolab.edu',
      department: 'Engineering',
      level: 'Level 2',
      section: 'ENG-2A',
      status: 'inactive',
      gpa: 2.94,
      enrolledSubjects: 4,
    ),
  ];

  List<StaffMember> staff() => const [
    StaffMember(
      id: 'SF-201',
      name: 'Dr. Hadeer Salah',
      email: 'hadeer.salah@tolab.edu',
      title: 'Doctor',
      department: 'Computer Science',
      subjects: 3,
      status: 'active',
    ),
    StaffMember(
      id: 'SF-202',
      name: 'Eng. Ahmed Samir',
      email: 'ahmed.samir@tolab.edu',
      title: 'Assistant',
      department: 'Information Systems',
      subjects: 4,
      status: 'active',
    ),
    StaffMember(
      id: 'SF-203',
      name: 'Dr. Reem Fawzy',
      email: 'reem.fawzy@tolab.edu',
      title: 'Doctor',
      department: 'Engineering',
      subjects: 2,
      status: 'blocked',
    ),
  ];

  List<StaffAdminRecord> staffDirectory() => [
    _staffRecord(
      id: 'DOC-401',
      fullName: 'Dr. Hadeer Salah',
      email: 'hadeer.salah@tolab.edu',
      employeeId: 'FCI-D-401',
      role: 'Doctor',
      doctorType: 'Internal faculty doctor',
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Leads Advanced Algorithms and student progress review.',
      recentActivity: 'Published lecture pack and reviewed task submissions.',
      createdAtLabel: 'Jan 05, 2026',
      lastActiveLabel: '10 minutes ago',
      attendanceRate: 96,
      engagementRate: 91,
      lecturesUploaded: 18,
      tasksCreated: 9,
      postsCreated: 22,
      uploadsCount: 31,
      scheduleUpdates: 5,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS401',
          title: 'Advanced Algorithms',
          section: 'Lecture hall A',
          lectures: 10,
          tasks: 5,
          posts: 11,
          uploads: 16,
          engagementRate: 92,
          status: 'Healthy',
        ),
        StaffSubjectAssignment(
          code: 'CS404',
          title: 'Compiler Design',
          section: 'Lecture hall C',
          lectures: 8,
          tasks: 4,
          posts: 11,
          uploads: 15,
          engagementRate: 88,
          status: 'Strong',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([95, 96, 97, 94, 96, 98, 96]),
      engagementTrend: _metricTrend([82, 86, 88, 89, 91, 93, 91]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Lecture package uploaded',
          subtitle:
              'Advanced Algorithms week 8 assets were synced successfully.',
          timeLabel: 'Today, 09:14',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Task due date adjusted',
          subtitle: 'Extended section task deadline after department review.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Attendance checkpoint completed',
          subtitle: 'Presence records stayed above the faculty target line.',
          timeLabel: '2 days ago',
          emphasis: 'strong',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-412',
      fullName: 'Dr. Mostafa Nader',
      email: 'mostafa.nader@tolab.edu',
      employeeId: 'FCI-D-412',
      role: 'Doctor',
      doctorType: 'Delegated / external doctor',
      department: 'Information Systems',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary:
          'Owns Enterprise Systems delivery and delegated schedule blocks.',
      recentActivity:
          'Posted case-study material and updated office-hour schedule.',
      createdAtLabel: 'Feb 12, 2026',
      lastActiveLabel: '1 hour ago',
      attendanceRate: 84,
      engagementRate: 79,
      lecturesUploaded: 12,
      tasksCreated: 6,
      postsCreated: 13,
      uploadsCount: 17,
      scheduleUpdates: 8,
      subjects: const [
        StaffSubjectAssignment(
          code: 'IS305',
          title: 'Enterprise Systems',
          section: 'Hybrid cohort B',
          lectures: 7,
          tasks: 3,
          posts: 8,
          uploads: 10,
          engagementRate: 81,
          status: 'On track',
        ),
        StaffSubjectAssignment(
          code: 'IS312',
          title: 'Business Intelligence',
          section: 'Lecture hall D',
          lectures: 5,
          tasks: 3,
          posts: 5,
          uploads: 7,
          engagementRate: 76,
          status: 'Monitor',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([78, 82, 83, 86, 85, 84, 84]),
      engagementTrend: _metricTrend([70, 72, 74, 77, 79, 80, 79]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Delegated account verified',
          subtitle: 'External contract details were synced with faculty admin.',
          timeLabel: 'Today, 08:10',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Schedule override requested',
          subtitle: 'Updated lecture slot pending final timetable review.',
          timeLabel: 'Yesterday',
          emphasis: 'attention',
        ),
        StaffTimelineEvent(
          title: 'Community posts reviewed',
          subtitle: 'Three course updates were published to the IS305 stream.',
          timeLabel: '3 days ago',
          emphasis: 'normal',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-425',
      fullName: 'Dr. Reem Fawzy',
      email: 'reem.fawzy@tolab.edu',
      employeeId: 'ENG-D-425',
      role: 'Doctor',
      doctorType: 'Internal faculty doctor',
      department: 'Engineering',
      status: 'Inactive',
      accountCreationStatus: 'Under review',
      roleSummary: 'Engineering doctor with limited current semester delivery.',
      recentActivity: 'Account paused pending renewed teaching allocation.',
      createdAtLabel: 'Dec 20, 2025',
      lastActiveLabel: '4 days ago',
      attendanceRate: 62,
      engagementRate: 58,
      lecturesUploaded: 4,
      tasksCreated: 2,
      postsCreated: 3,
      uploadsCount: 5,
      scheduleUpdates: 1,
      subjects: const [
        StaffSubjectAssignment(
          code: 'ENG210',
          title: 'Thermodynamics',
          section: 'Section E2',
          lectures: 2,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 59,
          status: 'Needs follow-up',
        ),
        StaffSubjectAssignment(
          code: 'ENG315',
          title: 'Control Systems',
          section: 'Lab C1',
          lectures: 2,
          tasks: 1,
          posts: 1,
          uploads: 2,
          engagementRate: 57,
          status: 'At risk',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: false,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([74, 70, 68, 66, 64, 63, 62]),
      engagementTrend: _metricTrend([66, 64, 63, 61, 60, 58, 58]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Account sent for review',
          subtitle: 'Access scope is waiting for department head confirmation.',
          timeLabel: 'Today, 11:40',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Attendance threshold missed',
          subtitle: 'Presence dipped below the preferred control range.',
          timeLabel: '2 days ago',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Content output slowed',
          subtitle: 'No new lecture materials were uploaded this week.',
          timeLabel: '4 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-437',
      fullName: 'Dr. Salma Adel',
      email: 'salma.adel@tolab.edu',
      employeeId: 'FCI-D-437',
      role: 'Doctor',
      doctorType: 'Delegated / external doctor',
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Invite pending',
      roleSummary: 'Delegated doctor covering AI electives and blended labs.',
      recentActivity:
          'Accepted subject assignment but has pending community permissions.',
      createdAtLabel: 'Mar 02, 2026',
      lastActiveLabel: '3 hours ago',
      attendanceRate: 77,
      engagementRate: 73,
      lecturesUploaded: 9,
      tasksCreated: 5,
      postsCreated: 7,
      uploadsCount: 12,
      scheduleUpdates: 2,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS470',
          title: 'Applied AI',
          section: 'Lecture hall F',
          lectures: 5,
          tasks: 3,
          posts: 4,
          uploads: 7,
          engagementRate: 75,
          status: 'Monitor',
        ),
        StaffSubjectAssignment(
          code: 'CS473',
          title: 'Neural Networks',
          section: 'Lab B4',
          lectures: 4,
          tasks: 2,
          posts: 3,
          uploads: 5,
          engagementRate: 72,
          status: 'On track',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([72, 74, 75, 76, 78, 79, 77]),
      engagementTrend: _metricTrend([68, 69, 70, 72, 74, 75, 73]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Account invitation pending',
          subtitle: 'Final activation email has not been accepted yet.',
          timeLabel: 'Today, 07:30',
          emphasis: 'attention',
        ),
        StaffTimelineEvent(
          title: 'Lecture content uploaded',
          subtitle:
              'AI elective materials were added to both assigned subjects.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Permissions review opened',
          subtitle: 'Community moderation scope is still awaiting approval.',
          timeLabel: '3 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-501',
      fullName: 'Eng. Ahmed Samir',
      email: 'ahmed.samir@tolab.edu',
      employeeId: 'IS-TA-501',
      role: 'Assistant',
      doctorType: null,
      department: 'Information Systems',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Primary section coordinator for enterprise labs.',
      recentActivity:
          'Closed student questions and uploaded lab support sheets.',
      createdAtLabel: 'Jan 18, 2026',
      lastActiveLabel: '18 minutes ago',
      attendanceRate: 93,
      engagementRate: 88,
      lecturesUploaded: 0,
      tasksCreated: 7,
      postsCreated: 18,
      uploadsCount: 26,
      scheduleUpdates: 4,
      subjects: const [
        StaffSubjectAssignment(
          code: 'IS305',
          title: 'Enterprise Systems',
          section: 'Section B1',
          lectures: 0,
          tasks: 4,
          posts: 10,
          uploads: 14,
          engagementRate: 89,
          status: 'Strong',
        ),
        StaffSubjectAssignment(
          code: 'IS204',
          title: 'Database Systems',
          section: 'Lab A2',
          lectures: 0,
          tasks: 3,
          posts: 8,
          uploads: 12,
          engagementRate: 87,
          status: 'Healthy',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: true,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([89, 90, 92, 94, 93, 95, 93]),
      engagementTrend: _metricTrend([80, 82, 84, 87, 88, 90, 88]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Section resources uploaded',
          subtitle:
              'Database Systems support materials were added to the lab area.',
          timeLabel: 'Today, 10:05',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Student questions resolved',
          subtitle: 'Eight forum items were answered across assigned subjects.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Attendance logged',
          subtitle: 'Assistant presence stayed above the target band all week.',
          timeLabel: '2 days ago',
          emphasis: 'strong',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-512',
      fullName: 'Eng. Menna Wael',
      email: 'menna.wael@tolab.edu',
      employeeId: 'FCI-TA-512',
      role: 'Assistant',
      doctorType: null,
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Teaching assistant supporting operating systems sections.',
      recentActivity:
          'Uploaded lab notes and monitored task discussion threads.',
      createdAtLabel: 'Jan 24, 2026',
      lastActiveLabel: '42 minutes ago',
      attendanceRate: 86,
      engagementRate: 81,
      lecturesUploaded: 0,
      tasksCreated: 6,
      postsCreated: 15,
      uploadsCount: 21,
      scheduleUpdates: 2,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS330',
          title: 'Operating Systems',
          section: 'Lab D3',
          lectures: 0,
          tasks: 4,
          posts: 9,
          uploads: 12,
          engagementRate: 83,
          status: 'Healthy',
        ),
        StaffSubjectAssignment(
          code: 'CS250',
          title: 'Data Structures',
          section: 'Section A1',
          lectures: 0,
          tasks: 2,
          posts: 6,
          uploads: 9,
          engagementRate: 78,
          status: 'On track',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([81, 82, 84, 85, 86, 87, 86]),
      engagementTrend: _metricTrend([75, 77, 78, 80, 82, 83, 81]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Section content refreshed',
          subtitle: 'Operating Systems lab tasks were updated with new hints.',
          timeLabel: 'Today, 08:42',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Upload queue completed',
          subtitle: 'All support PDFs were synchronized successfully.',
          timeLabel: 'Yesterday',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Schedule update declined',
          subtitle: 'Requested lab swap needs doctor-level approval first.',
          timeLabel: '4 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-526',
      fullName: 'Eng. Nourhan Essam',
      email: 'nourhan.essam@tolab.edu',
      employeeId: 'ENG-TA-526',
      role: 'Assistant',
      doctorType: null,
      department: 'Engineering',
      status: 'Inactive',
      accountCreationStatus: 'Suspended',
      roleSummary: 'Assistant profile with paused semester access.',
      recentActivity:
          'Temporary suspension was applied after attendance review.',
      createdAtLabel: 'Nov 30, 2025',
      lastActiveLabel: '6 days ago',
      attendanceRate: 68,
      engagementRate: 61,
      lecturesUploaded: 0,
      tasksCreated: 2,
      postsCreated: 4,
      uploadsCount: 6,
      scheduleUpdates: 1,
      subjects: const [
        StaffSubjectAssignment(
          code: 'ENG120',
          title: 'Engineering Drawing',
          section: 'Lab E1',
          lectures: 0,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 63,
          status: 'At risk',
        ),
        StaffSubjectAssignment(
          code: 'ENG221',
          title: 'Mechanics',
          section: 'Section M2',
          lectures: 0,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 59,
          status: 'Needs follow-up',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: false,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([76, 74, 72, 70, 69, 68, 68]),
      engagementTrend: _metricTrend([69, 67, 65, 64, 63, 61, 61]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Assistant access suspended',
          subtitle: 'Profile is paused until faculty monitoring review closes.',
          timeLabel: 'Today, 12:15',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Attendance warning raised',
          subtitle:
              'Presence score stayed below the expected line for two weeks.',
          timeLabel: 'Yesterday',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Content permissions restricted',
          subtitle: 'Upload and posting scope were reduced automatically.',
          timeLabel: '3 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-538',
      fullName: 'Eng. Omar Adel',
      email: 'omar.adel.staff@tolab.edu',
      employeeId: 'FCI-TA-538',
      role: 'Assistant',
      doctorType: null,
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary:
          'Assistant handling community follow-up and material uploads.',
      recentActivity: 'Managed course posts and prepared this week lab sheets.',
      createdAtLabel: 'Feb 05, 2026',
      lastActiveLabel: '27 minutes ago',
      attendanceRate: 90,
      engagementRate: 85,
      lecturesUploaded: 0,
      tasksCreated: 5,
      postsCreated: 20,
      uploadsCount: 19,
      scheduleUpdates: 3,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS290',
          title: 'Web Engineering',
          section: 'Lab W1',
          lectures: 0,
          tasks: 3,
          posts: 12,
          uploads: 11,
          engagementRate: 86,
          status: 'Strong',
        ),
        StaffSubjectAssignment(
          code: 'CS315',
          title: 'Software Testing',
          section: 'Section T2',
          lectures: 0,
          tasks: 2,
          posts: 8,
          uploads: 8,
          engagementRate: 84,
          status: 'Healthy',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([86, 87, 89, 90, 90, 91, 90]),
      engagementTrend: _metricTrend([79, 80, 82, 84, 86, 86, 85]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Course post moderation complete',
          subtitle: 'Discussion posts were triaged and pinned for students.',
          timeLabel: 'Today, 09:55',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Task instructions uploaded',
          subtitle:
              'New testing-lab instructions were shared with both sections.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Schedule patch approved',
          subtitle:
              'Assistant received permission to update one lab session slot.',
          timeLabel: '2 days ago',
          emphasis: 'normal',
        ),
      ],
    ),
  ];

  List<DepartmentModel> departments() => const [
    DepartmentModel(
      id: 'DEP-1',
      name: 'Computer Science',
      code: 'CS',
      head: 'Dr. Eman Adel',
      status: 'active',
      studentsCount: 3120,
    ),
    DepartmentModel(
      id: 'DEP-2',
      name: 'Information Systems',
      code: 'IS',
      head: 'Dr. Nader Mostafa',
      status: 'active',
      studentsCount: 2540,
    ),
  ];

  List<SectionModel> sections() => const [
    SectionModel(
      id: 'SEC-1',
      name: 'CS-4A',
      department: 'Computer Science',
      year: '2025/2026',
      semester: 'Spring',
      status: 'active',
    ),
    SectionModel(
      id: 'SEC-2',
      name: 'IS-3B',
      department: 'Information Systems',
      year: '2025/2026',
      semester: 'Spring',
      status: 'active',
    ),
  ];

  List<SubjectRecord> subjects() => [
    SubjectRecord(
      id: 'SUB-401',
      code: 'CS401',
      name: 'Advanced Algorithms',
      department: 'Computer Science',
      academicYear: 'Year 4',
      creditHours: 3,
      contactHours: 5,
      status: 'Active',
      doctor: const SubjectStaffMember(
        id: 'DOC-401',
        name: 'Dr. Hadeer Salah',
        role: 'Doctor',
        email: 'hadeer.salah@tolab.edu',
        channelLabel: 'Algorithms faculty channel',
        status: 'Live',
        color: AppColors.primary,
      ),
      assistant: const SubjectStaffMember(
        id: 'TA-512',
        name: 'Eng. Menna Wael',
        role: 'Assistant',
        email: 'menna.wael@tolab.edu',
        channelLabel: 'Section lab support',
        status: 'Live',
        color: AppColors.info,
      ),
      eligibleStudents: 160,
      enrolledStudents: 142,
      group: const SubjectGroupInfo(
        enabled: true,
        name: 'Algorithms Studio',
        members: 151,
        moderationLabel: 'Doctor + assistant moderators',
        engagementLabel: 'High engagement',
      ),
      posts: const SubjectPostsInfo(
        count: 36,
        openingScope: 'Staff opens posts',
        monitoringScope: 'Admin + doctor monitor',
        recent: [
          SubjectPostItem(
            title: 'Week 8 complexity clinic',
            author: 'Dr. Hadeer Salah',
            timeLabel: '12 min ago',
            status: 'Pinned',
          ),
          SubjectPostItem(
            title: 'Late registration notice',
            author: 'Admin Academic Office',
            timeLabel: '1h ago',
            status: 'Open',
          ),
          SubjectPostItem(
            title: 'Lab guide uploaded',
            author: 'Eng. Menna Wael',
            timeLabel: 'Yesterday',
            status: 'Reviewed',
          ),
        ],
      ),
      summaries: const SubjectSummariesInfo(
        count: 12,
        accessScope: 'Students can view summaries',
        latest: [
          SubjectSummaryItem(
            title: 'Graph optimization recap',
            versionLabel: 'v3',
            updatedAtLabel: 'Today',
          ),
          SubjectSummaryItem(
            title: 'DP pattern cheat sheet',
            versionLabel: 'v2',
            updatedAtLabel: 'Yesterday',
          ),
        ],
      ),
      access: const SubjectAccessInfo(
        code: 'ALG-9X2P',
        link: 'tolab.edu/join/cs401-alg',
        lateJoinLabel: 'Late registration allowed through code and link',
        regeneratedAtLabel: 'Regenerated 2 days ago',
      ),
      permissions: _subjectPermissions(
        allowStudentPosts: false,
        allowStaffPostModeration: true,
        summariesVisibleToStudents: true,
        studentListVisibleToDoctor: true,
        studentListVisibleToAssistant: true,
        staffOnlyStudentVisibility: true,
        lateRegistrationEnabled: true,
      ),
      students: const [
        SubjectStudentItem(
          id: 'ST-1001',
          name: 'Omar Adel',
          section: 'CS-4A',
          level: 'Level 4',
          status: 'Enrolled',
          privacyLabel: 'Hidden from peers',
          lateJoin: false,
        ),
        SubjectStudentItem(
          id: 'ST-1084',
          name: 'Salma Emad',
          section: 'CS-4B',
          level: 'Level 4',
          status: 'Enrolled',
          privacyLabel: 'Hidden from peers',
          lateJoin: true,
        ),
        SubjectStudentItem(
          id: 'ST-1112',
          name: 'Ziad Wael',
          section: 'CS-4A',
          level: 'Level 4',
          status: 'Eligible',
          privacyLabel: 'Visible to staff only',
          lateJoin: false,
        ),
      ],
      timeline: const [
        SubjectTimelineEvent(
          title: 'Late registration joined',
          subtitle: 'Four students entered through the secure link flow.',
          timeLabel: 'Today, 09:20',
          tone: 'warning',
        ),
        SubjectTimelineEvent(
          title: 'Pinned post updated',
          subtitle: 'Doctor refreshed the exam preparation guidance.',
          timeLabel: 'Today, 08:05',
          tone: 'info',
        ),
        SubjectTimelineEvent(
          title: 'Summary bundle uploaded',
          subtitle: 'Teaching assistant added revision material set B.',
          timeLabel: 'Yesterday',
          tone: 'success',
        ),
      ],
      activity: const [
        SubjectActivityPoint('Mon', 58),
        SubjectActivityPoint('Tue', 66),
        SubjectActivityPoint('Wed', 61),
        SubjectActivityPoint('Thu', 74),
        SubjectActivityPoint('Fri', 81),
        SubjectActivityPoint('Sat', 77),
        SubjectActivityPoint('Sun', 84),
      ],
      updatedAtLabel: 'Updated 12 min ago',
      lateRegistrationEnabled: true,
    ),
    SubjectRecord(
      id: 'SUB-305',
      code: 'IS305',
      name: 'Enterprise Systems',
      department: 'Information Systems',
      academicYear: 'Year 3',
      creditHours: 3,
      contactHours: 4,
      status: 'Active',
      doctor: const SubjectStaffMember(
        id: 'DOC-412',
        name: 'Dr. Mostafa Nader',
        role: 'Doctor',
        email: 'mostafa.nader@tolab.edu',
        channelLabel: 'Enterprise strategy channel',
        status: 'Live',
        color: AppColors.primary,
      ),
      assistant: const SubjectStaffMember(
        id: 'TA-501',
        name: 'Eng. Ahmed Samir',
        role: 'Assistant',
        email: 'ahmed.samir@tolab.edu',
        channelLabel: 'Lab and section desk',
        status: 'Live',
        color: AppColors.info,
      ),
      eligibleStudents: 120,
      enrolledStudents: 98,
      group: const SubjectGroupInfo(
        enabled: true,
        name: 'Enterprise Cohort',
        members: 104,
        moderationLabel: 'Assistant moderates student threads',
        engagementLabel: 'Stable engagement',
      ),
      posts: const SubjectPostsInfo(
        count: 24,
        openingScope: 'Students request, staff publish',
        monitoringScope: 'Doctor + assistant monitor',
        recent: [
          SubjectPostItem(
            title: 'Case study discussion board',
            author: 'Eng. Ahmed Samir',
            timeLabel: '45 min ago',
            status: 'Open',
          ),
          SubjectPostItem(
            title: 'Project briefing pinned',
            author: 'Dr. Mostafa Nader',
            timeLabel: 'Today',
            status: 'Pinned',
          ),
        ],
      ),
      summaries: const SubjectSummariesInfo(
        count: 8,
        accessScope: 'Students and staff',
        latest: [
          SubjectSummaryItem(
            title: 'ERP implementation map',
            versionLabel: 'v1',
            updatedAtLabel: 'Today',
          ),
          SubjectSummaryItem(
            title: 'SOA revision summary',
            versionLabel: 'v4',
            updatedAtLabel: '2 days ago',
          ),
        ],
      ),
      access: const SubjectAccessInfo(
        code: 'ENT-54LM',
        link: 'tolab.edu/join/is305-ent',
        lateJoinLabel: 'Late join enabled for transferred students',
        regeneratedAtLabel: 'Regenerated today',
      ),
      permissions: _subjectPermissions(
        allowStudentPosts: true,
        allowStaffPostModeration: true,
        summariesVisibleToStudents: true,
        studentListVisibleToDoctor: true,
        studentListVisibleToAssistant: true,
        staffOnlyStudentVisibility: true,
        lateRegistrationEnabled: true,
      ),
      students: const [
        SubjectStudentItem(
          id: 'ST-1002',
          name: 'Mariam Tarek',
          section: 'IS-3B',
          level: 'Level 3',
          status: 'Enrolled',
          privacyLabel: 'Hidden from peers',
          lateJoin: false,
        ),
        SubjectStudentItem(
          id: 'ST-1160',
          name: 'Nada Sabry',
          section: 'IS-3A',
          level: 'Level 3',
          status: 'Enrolled',
          privacyLabel: 'Visible to staff only',
          lateJoin: true,
        ),
      ],
      timeline: const [
        SubjectTimelineEvent(
          title: 'Access link regenerated',
          subtitle: 'Admin refreshed the join link after transfer intake.',
          timeLabel: 'Today, 11:42',
          tone: 'info',
        ),
        SubjectTimelineEvent(
          title: 'Summary review published',
          subtitle: 'Revision package shared with enrolled students.',
          timeLabel: 'Yesterday',
          tone: 'success',
        ),
      ],
      activity: const [
        SubjectActivityPoint('Mon', 45),
        SubjectActivityPoint('Tue', 51),
        SubjectActivityPoint('Wed', 57),
        SubjectActivityPoint('Thu', 63),
        SubjectActivityPoint('Fri', 70),
        SubjectActivityPoint('Sat', 67),
        SubjectActivityPoint('Sun', 72),
      ],
      updatedAtLabel: 'Updated 45 min ago',
      lateRegistrationEnabled: true,
    ),
    SubjectRecord(
      id: 'SUB-330',
      code: 'CS330',
      name: 'Operating Systems',
      department: 'Computer Science',
      academicYear: 'Year 3',
      creditHours: 4,
      contactHours: 6,
      status: 'Monitor',
      doctor: const SubjectStaffMember(
        id: 'DOC-437',
        name: 'Dr. Salma Adel',
        role: 'Doctor',
        email: 'salma.adel@tolab.edu',
        channelLabel: 'Systems academic channel',
        status: 'Pending invite',
        color: AppColors.primary,
      ),
      assistant: const SubjectStaffMember(
        id: 'TA-538',
        name: 'Eng. Omar Adel',
        role: 'Assistant',
        email: 'omar.adel.staff@tolab.edu',
        channelLabel: 'OS lab supervision',
        status: 'Live',
        color: AppColors.info,
      ),
      eligibleStudents: 140,
      enrolledStudents: 117,
      group: const SubjectGroupInfo(
        enabled: true,
        name: 'Kernel Lab Circle',
        members: 121,
        moderationLabel: 'Assistant-led moderation',
        engagementLabel: 'Watch activity',
      ),
      posts: const SubjectPostsInfo(
        count: 31,
        openingScope: 'Staff only',
        monitoringScope: 'Admin + assistant monitor',
        recent: [
          SubjectPostItem(
            title: 'Thread scheduling FAQ',
            author: 'Eng. Omar Adel',
            timeLabel: '2h ago',
            status: 'Reviewed',
          ),
          SubjectPostItem(
            title: 'Doctor access still pending',
            author: 'Admin Academic Office',
            timeLabel: 'Yesterday',
            status: 'Flagged',
          ),
        ],
      ),
      summaries: const SubjectSummariesInfo(
        count: 6,
        accessScope: 'Staff curated access',
        latest: [
          SubjectSummaryItem(
            title: 'Memory management recap',
            versionLabel: 'v2',
            updatedAtLabel: 'Today',
          ),
        ],
      ),
      access: const SubjectAccessInfo(
        code: 'OPS-71RK',
        link: 'tolab.edu/join/cs330-ops',
        lateJoinLabel:
            'Late registration paused until doctor invite acceptance',
        regeneratedAtLabel: 'Regenerated 5 days ago',
      ),
      permissions: _subjectPermissions(
        allowStudentPosts: false,
        allowStaffPostModeration: true,
        summariesVisibleToStudents: false,
        studentListVisibleToDoctor: true,
        studentListVisibleToAssistant: true,
        staffOnlyStudentVisibility: true,
        lateRegistrationEnabled: false,
      ),
      students: const [
        SubjectStudentItem(
          id: 'ST-1201',
          name: 'Karim Nabil',
          section: 'CS-3C',
          level: 'Level 3',
          status: 'Enrolled',
          privacyLabel: 'Hidden from peers',
          lateJoin: false,
        ),
        SubjectStudentItem(
          id: 'ST-1205',
          name: 'Rana Adel',
          section: 'CS-3D',
          level: 'Level 3',
          status: 'Eligible',
          privacyLabel: 'Staff only',
          lateJoin: false,
        ),
      ],
      timeline: const [
        SubjectTimelineEvent(
          title: 'Doctor account invite pending',
          subtitle: 'Subject remains under monitoring until invite acceptance.',
          timeLabel: 'Today, 07:30',
          tone: 'warning',
        ),
        SubjectTimelineEvent(
          title: 'Student posts restricted',
          subtitle: 'Community posting remains staff-led this week.',
          timeLabel: 'Yesterday',
          tone: 'critical',
        ),
      ],
      activity: const [
        SubjectActivityPoint('Mon', 38),
        SubjectActivityPoint('Tue', 46),
        SubjectActivityPoint('Wed', 40),
        SubjectActivityPoint('Thu', 55),
        SubjectActivityPoint('Fri', 52),
        SubjectActivityPoint('Sat', 50),
        SubjectActivityPoint('Sun', 60),
      ],
      updatedAtLabel: 'Updated 2h ago',
      lateRegistrationEnabled: false,
    ),
    SubjectRecord(
      id: 'SUB-210',
      code: 'ENG210',
      name: 'Thermodynamics',
      department: 'Engineering',
      academicYear: 'Year 2',
      creditHours: 3,
      contactHours: 4,
      status: 'Draft',
      doctor: const SubjectStaffMember(
        id: 'DOC-425',
        name: 'Dr. Reem Fawzy',
        role: 'Doctor',
        email: 'reem.fawzy@tolab.edu',
        channelLabel: 'Engineering faculty stream',
        status: 'Under review',
        color: AppColors.primary,
      ),
      assistant: const SubjectStaffMember(
        id: 'TA-526',
        name: 'Eng. Nourhan Essam',
        role: 'Assistant',
        email: 'nourhan.essam@tolab.edu',
        channelLabel: 'Engineering section support',
        status: 'Suspended',
        color: AppColors.info,
      ),
      eligibleStudents: 90,
      enrolledStudents: 54,
      group: const SubjectGroupInfo(
        enabled: false,
        name: 'No community yet',
        members: 0,
        moderationLabel: 'Community not created',
        engagementLabel: 'No engagement',
      ),
      posts: const SubjectPostsInfo(
        count: 4,
        openingScope: 'Closed until publish',
        monitoringScope: 'Admin only',
        recent: [
          SubjectPostItem(
            title: 'Draft syllabus review',
            author: 'Admin Academic Office',
            timeLabel: '2 days ago',
            status: 'Draft',
          ),
        ],
      ),
      summaries: const SubjectSummariesInfo(
        count: 2,
        accessScope: 'Staff only',
        latest: [
          SubjectSummaryItem(
            title: 'Heat transfer intro',
            versionLabel: 'v1',
            updatedAtLabel: 'Yesterday',
          ),
        ],
      ),
      access: const SubjectAccessInfo(
        code: 'THERM-00',
        link: 'tolab.edu/join/eng210-draft',
        lateJoinLabel: 'Access disabled until publishing',
        regeneratedAtLabel: 'Never regenerated',
      ),
      permissions: _subjectPermissions(
        allowStudentPosts: false,
        allowStaffPostModeration: false,
        summariesVisibleToStudents: false,
        studentListVisibleToDoctor: false,
        studentListVisibleToAssistant: false,
        staffOnlyStudentVisibility: true,
        lateRegistrationEnabled: false,
      ),
      students: const [
        SubjectStudentItem(
          id: 'ST-1301',
          name: 'Mina Atef',
          section: 'ENG-2A',
          level: 'Level 2',
          status: 'Eligible',
          privacyLabel: 'Staff only',
          lateJoin: false,
        ),
      ],
      timeline: const [
        SubjectTimelineEvent(
          title: 'Publishing blocked',
          subtitle: 'Doctor and assistant accounts need reactivation first.',
          timeLabel: 'Today, 12:10',
          tone: 'critical',
        ),
      ],
      activity: const [
        SubjectActivityPoint('Mon', 12),
        SubjectActivityPoint('Tue', 16),
        SubjectActivityPoint('Wed', 18),
        SubjectActivityPoint('Thu', 22),
        SubjectActivityPoint('Fri', 19),
        SubjectActivityPoint('Sat', 17),
        SubjectActivityPoint('Sun', 20),
      ],
      updatedAtLabel: 'Updated today',
      lateRegistrationEnabled: false,
    ),
  ];

  List<CourseOfferingModel> courseOfferings() => const [
    CourseOfferingModel(
      id: 'OFF-1',
      subjectCode: 'CS401',
      subjectName: 'Advanced Algorithms',
      sectionName: 'CS-4A',
      doctorName: 'Dr. Hadeer Salah',
      assistantName: 'Eng. Ahmed Samir',
      semester: 'Spring 2026',
      enrolled: 88,
      capacity: 100,
      status: 'active',
    ),
    CourseOfferingModel(
      id: 'OFF-2',
      subjectCode: 'IS305',
      subjectName: 'Enterprise Systems',
      sectionName: 'IS-3B',
      doctorName: 'Dr. Reem Fawzy',
      assistantName: 'Eng. Ahmed Samir',
      semester: 'Spring 2026',
      enrolled: 76,
      capacity: 80,
      status: 'pending',
    ),
  ];

  List<EnrollmentRecord> enrollments() => const [
    EnrollmentRecord(
      id: 'ENR-1',
      studentName: 'Omar Adel',
      subjectName: 'Advanced Algorithms',
      department: 'Computer Science',
      level: 'Level 4',
      status: 'active',
    ),
    EnrollmentRecord(
      id: 'ENR-2',
      studentName: 'Mariam Tarek',
      subjectName: 'Enterprise Systems',
      department: 'Information Systems',
      level: 'Level 3',
      status: 'active',
    ),
  ];

  List<ContentItem> contentItems() => const [
    ContentItem(
      id: 'CNT-1',
      courseTitle: 'Advanced Algorithms',
      type: 'Lecture',
      title: 'Greedy Optimization Patterns',
      status: 'published',
      attachments: 3,
      dueDateLabel: 'Apr 14, 2026',
    ),
    ContentItem(
      id: 'CNT-2',
      courseTitle: 'Enterprise Systems',
      type: 'Quiz',
      title: 'Week 5 Assessment',
      status: 'scheduled',
      attachments: 1,
      dueDateLabel: 'Apr 20, 2026',
    ),
  ];

  List<UploadItem> uploads() => const [
    UploadItem(
      id: 'UP-1',
      name: 'semester-schedule.xlsx',
      sizeLabel: '2.8 MB',
      progress: 1,
      status: 'completed',
      mimeType: 'application/vnd.ms-excel',
    ),
    UploadItem(
      id: 'UP-2',
      name: 'lecture-assets.zip',
      sizeLabel: '84 MB',
      progress: .54,
      status: 'uploading',
      mimeType: 'application/zip',
    ),
  ];

  List<ScheduleEventModel> scheduleEvents() {
    final now = DateTime.now();
    return [
      ScheduleEventModel(
        id: 'EV-1',
        title: 'Lecture 08',
        course: 'Advanced Algorithms',
        instructor: 'Dr. Hadeer Salah',
        location: 'Hall B12',
        type: 'lecture',
        status: 'planned',
        start: DateTime(now.year, now.month, now.day, 9),
        end: DateTime(now.year, now.month, now.day, 11),
        color: AppColors.primary,
      ),
      ScheduleEventModel(
        id: 'EV-2',
        title: 'Section Review',
        course: 'Enterprise Systems',
        instructor: 'Eng. Ahmed Samir',
        location: 'Lab C3',
        type: 'section',
        status: 'completed',
        start: DateTime(now.year, now.month, now.day + 1, 12),
        end: DateTime(now.year, now.month, now.day + 1, 14),
        color: AppColors.secondary,
      ),
      ScheduleEventModel(
        id: 'EV-3',
        title: 'Midterm Exam',
        course: 'Operating Systems',
        instructor: 'Dr. Reem Fawzy',
        location: 'Main Auditorium',
        type: 'exam',
        status: 'planned',
        start: DateTime(now.year, now.month, now.day + 3, 10),
        end: DateTime(now.year, now.month, now.day + 3, 12),
        color: AppColors.warning,
      ),
    ];
  }

  List<AdminNotification> notifications() {
    final now = DateTime.now();
    return [
      AdminNotification(
        id: 'NT-1',
        title: 'New student registration requires approval',
        body:
            'Maha El-Sayed submitted a late enrollment request for CS-4A and is waiting for an admin approval slot.',
        category: AdminNotificationCategory.academic,
        createdAt: now.subtract(const Duration(minutes: 4)),
        isRead: false,
        rawType: 'GRADE',
        refType: 'enrollment',
        refId: 'ENR-921',
        source: 'seed',
        audienceLabel: 'Admissions desk',
      ),
      AdminNotification(
        id: 'NT-2',
        title: 'Department schedule changed',
        body:
            'Operating Systems lecture moved from Hall C2 to Hall A4 after a room conflict was resolved.',
        category: AdminNotificationCategory.academic,
        createdAt: now.subtract(const Duration(minutes: 18)),
        isRead: false,
        rawType: 'SCHEDULE',
        refType: 'schedule',
        refId: 'SCH-CONFLICT-2',
        source: 'seed',
        audienceLabel: 'Computer Science',
      ),
      AdminNotification(
        id: 'NT-3',
        title: 'Unread staff message escalation',
        body:
            'Two students reported an unanswered thread inside Enterprise Systems section B1.',
        category: AdminNotificationCategory.messages,
        createdAt: now.subtract(const Duration(minutes: 46)),
        isRead: false,
        rawType: 'MODERATION',
        refType: 'message',
        refId: 'MSG-441',
        source: 'seed',
        audienceLabel: 'Staff moderation',
      ),
      AdminNotification(
        id: 'NT-4',
        title: 'Campus-wide announcement queued',
        body:
            'Spring midterm seat allocation announcement is scheduled for delivery to all undergraduate cohorts.',
        category: AdminNotificationCategory.announcements,
        createdAt: now.subtract(const Duration(hours: 2, minutes: 15)),
        isRead: false,
        rawType: 'CONTENT',
        refType: 'announcement',
        refId: 'ANN-302',
        source: 'seed',
        audienceLabel: 'All students',
      ),
      AdminNotification(
        id: 'NT-5',
        title: 'Security policy updated',
        body:
            'A new two-step verification recommendation is now available for admin accounts.',
        category: AdminNotificationCategory.system,
        createdAt: now.subtract(const Duration(hours: 6)),
        isRead: true,
        rawType: 'SYSTEM',
        refType: 'settings',
        refId: 'SEC-11',
        source: 'seed',
        audienceLabel: 'Administrators',
      ),
      AdminNotification(
        id: 'NT-6',
        title: 'Task submission spike detected',
        body:
            'Advanced Algorithms crossed the expected upload rate and generated 87 submissions in the last hour.',
        category: AdminNotificationCategory.academic,
        createdAt: now.subtract(const Duration(days: 1, hours: 1)),
        isRead: true,
        rawType: 'GRADE',
        refType: 'content',
        refId: 'TASK-81',
        source: 'seed',
        audienceLabel: 'Faculty analytics',
      ),
      AdminNotification(
        id: 'NT-7',
        title: 'Broadcast delivery completed',
        body:
            'The registration deadline alert was delivered successfully to 4,218 recipients with no failures.',
        category: AdminNotificationCategory.announcements,
        createdAt: now.subtract(const Duration(days: 2, hours: 4)),
        isRead: true,
        rawType: 'BROADCAST',
        refType: 'campaign',
        refId: 'CMP-77',
        source: 'seed',
        audienceLabel: 'Level 3 students',
      ),
      AdminNotification(
        id: 'NT-8',
        title: 'Moderator response sent',
        body:
            'A flagged chat message was reviewed and the student received an official reply from moderation.',
        category: AdminNotificationCategory.messages,
        createdAt: now.subtract(const Duration(days: 5, hours: 3)),
        isRead: true,
        rawType: 'MODERATION',
        refType: 'message',
        refId: 'MSG-144',
        source: 'seed',
        audienceLabel: 'Moderation hub',
      ),
    ];
  }

  List<ModerationItem> moderationItems() => const [
    ModerationItem(
      id: 'MOD-1',
      type: 'Post',
      author: 'Mahmoud Ashraf',
      groupName: 'CS-4A',
      preview: 'Thread contains duplicated external links.',
      reportsCount: 4,
      status: 'flagged',
      createdAtLabel: '18 min ago',
    ),
    ModerationItem(
      id: 'MOD-2',
      type: 'Message',
      author: 'Sara Emad',
      groupName: 'IS-3B',
      preview: 'Potential harassment phrase detected by policy filter.',
      reportsCount: 2,
      status: 'pending',
      createdAtLabel: '1h ago',
    ),
  ];

  List<RolePermission> roles() => const [
    RolePermission(
      id: 'ROLE-1',
      role: 'Super Admin',
      members: 3,
      permissions: {
        'manage_users': true,
        'manage_schedule': true,
        'moderate_groups': true,
        'broadcast_notifications': true,
      },
    ),
    RolePermission(
      id: 'ROLE-2',
      role: 'Moderator',
      members: 8,
      permissions: {
        'manage_users': false,
        'manage_schedule': false,
        'moderate_groups': true,
        'broadcast_notifications': false,
      },
    ),
  ];

  SettingsBundle settings() {
    final now = DateTime.now();
    return SettingsBundle(
      general: const GeneralSettings(
        appName: 'Tolab Admin',
        academyName: 'Tolab Academy',
        logoUrl: 'assets/icons/iconapp.png',
        timezone: 'Africa/Cairo',
        languageCode: 'en',
      ),
      theme: const ThemeSettings(
        themeMode: ThemeMode.light,
        primaryColor: AppColors.primary,
        secondaryColor: AppColors.info,
        glassmorphismEnabled: true,
        cardBlurSigma: 18,
      ),
      notifications: const NotificationPreferences(
        pushEnabled: true,
        desktopAlertsEnabled: true,
        localAlertsEnabled: true,
        emailDigestEnabled: false,
        toastEnabled: true,
        soundEnabled: true,
        categories: {
          AdminNotificationCategory.academic: true,
          AdminNotificationCategory.messages: true,
          AdminNotificationCategory.system: true,
          AdminNotificationCategory.announcements: true,
        },
      ),
      security: SecuritySettings(
        passwordPolicy: const PasswordPolicy(
          minLength: 10,
          passwordExpiryDays: 90,
          requireUppercase: true,
          requireLowercase: true,
          requireNumbers: true,
          requireSpecialCharacters: true,
        ),
        sessionTimeoutMinutes: 45,
        twoFactorRequired: true,
        lockOnSuspiciousActivity: true,
        blockedAccounts: [
          BlockedAccount(
            id: 'blocked-1',
            name: 'Reem Fawzy',
            email: 'reem.fawzy@tolab.edu',
            reason: 'Repeated failed admin sign-ins',
            blockedAt: now.subtract(const Duration(days: 3)),
            isTemporary: true,
          ),
          BlockedAccount(
            id: 'blocked-2',
            name: 'Guest Account 04',
            email: 'guest04@tolab.edu',
            reason: 'Role misuse review',
            blockedAt: now.subtract(const Duration(days: 11)),
            isTemporary: false,
          ),
        ],
      ),
      userManagement: const UserManagementSettings(
        defaultRole: 'Academic Admin',
        allowStaffAdminAccess: true,
        requireApprovalForAdminAccess: true,
        allowRoleCloning: true,
        roleTemplates: [
          RolePermissionTemplate(
            id: 'role-1',
            name: 'Academic Admin',
            adminAccess: true,
            staffAccess: true,
            permissions: {
              'manage_users': true,
              'manage_schedule': true,
              'approve_uploads': true,
              'view_logs': true,
            },
          ),
          RolePermissionTemplate(
            id: 'role-2',
            name: 'Operations Lead',
            adminAccess: true,
            staffAccess: true,
            permissions: {
              'manage_users': false,
              'manage_schedule': true,
              'approve_uploads': true,
              'view_logs': true,
            },
          ),
          RolePermissionTemplate(
            id: 'role-3',
            name: 'Support Admin',
            adminAccess: false,
            staffAccess: true,
            permissions: {
              'manage_users': false,
              'manage_schedule': false,
              'approve_uploads': true,
              'view_logs': false,
            },
          ),
        ],
      ),
      uploadRules: const UploadRulesSettings(
        maxFileSizeMb: 250,
        allowedFileTypes: ['pdf', 'docx', 'xlsx', 'jpg', 'png', 'zip'],
        storageLocation: StorageLocation.s3,
        basePath: 'academy/uploads',
        validateMimeType: true,
        runVirusScan: true,
        renameOnUpload: false,
      ),
      calendar: CalendarSettings(
        defaultView: CalendarViewOption.week,
        typeColors: const {
          'Lecture': AppColors.primary,
          'Section': AppColors.secondary,
          'Exam': AppColors.warning,
          'Holiday': AppColors.danger,
        },
        holidays: [
          HolidayItem(
            id: 'holiday-1',
            name: 'Eid Holiday',
            date: now.add(const Duration(days: 14)),
            type: 'National',
          ),
          HolidayItem(
            id: 'holiday-2',
            name: 'Midterm Break',
            date: now.add(const Duration(days: 41)),
            type: 'Academic',
          ),
        ],
      ),
      system: SystemSettings(
        apiBaseUrl: 'http://127.0.0.1:8000/api',
        websocketUrl: 'ws://127.0.0.1:8000/ws/admin/notifications',
        apiKeys: [
          ApiCredential(
            id: 'cred-1',
            label: 'Laravel Sanctum',
            valueMasked: 'sk-live-9F2A****',
            scope: 'auth',
            lastRotatedAt: now.subtract(const Duration(days: 21)),
            isEnabled: true,
          ),
          ApiCredential(
            id: 'cred-2',
            label: 'Firebase Messaging',
            valueMasked: 'fcm-prod-C84****',
            scope: 'notifications',
            lastRotatedAt: now.subtract(const Duration(days: 8)),
            isEnabled: true,
          ),
        ],
        maintenanceMode: false,
        auditLoggingEnabled: true,
        logRetentionDays: 30,
        enableLaravelBroadcasting: true,
        integrationStatus: 'Connected',
      ),
      backupRestore: BackupRestoreSettings(
        autoBackupEnabled: true,
        frequency: BackupFrequency.daily,
        nextBackupAt: now.add(const Duration(days: 1, hours: 2)),
        storageTarget: 's3://tolab-backups/admin',
        retentionCount: 12,
        encryptBackups: true,
        history: [
          BackupSnapshot(
            id: 'backup-1',
            label: 'Nightly backup',
            createdAt: now.subtract(const Duration(hours: 10)),
            sizeLabel: '2.1 MB',
            status: 'Ready',
            source: 'laravel',
            restorable: true,
          ),
          BackupSnapshot(
            id: 'backup-2',
            label: 'Pre-release snapshot',
            createdAt: now.subtract(const Duration(days: 2)),
            sizeLabel: '2.0 MB',
            status: 'Ready',
            source: 'laravel',
            restorable: true,
          ),
        ],
      ),
      updatedAt: now.subtract(const Duration(minutes: 38)),
      source: 'seed',
      isSynced: true,
    );
  }

  StaffAdminRecord _staffRecord({
    required String id,
    required String fullName,
    required String email,
    required String employeeId,
    required String role,
    required String? doctorType,
    required String department,
    required String status,
    required String accountCreationStatus,
    required String roleSummary,
    required String recentActivity,
    required String createdAtLabel,
    required String lastActiveLabel,
    required double attendanceRate,
    required double engagementRate,
    required int lecturesUploaded,
    required int tasksCreated,
    required int postsCreated,
    required int uploadsCount,
    required int scheduleUpdates,
    required List<StaffSubjectAssignment> subjects,
    required List<StaffPermissionGroup> permissionGroups,
    required List<StaffTimelineEvent> timeline,
    required List<StaffMetricPoint> attendanceTrend,
    required List<StaffMetricPoint> engagementTrend,
  }) {
    final totalPermissions = permissionGroups.fold<int>(
      0,
      (sum, group) => sum + group.permissions.length,
    );
    final enabledPermissions = permissionGroups.fold<int>(
      0,
      (sum, group) =>
          sum +
          group.permissions.where((permission) => permission.enabled).length,
    );

    return StaffAdminRecord(
      id: id,
      fullName: fullName,
      email: email,
      employeeId: employeeId,
      role: role,
      doctorType: doctorType,
      department: department,
      status: status,
      accountCreationStatus: accountCreationStatus,
      roleSummary: roleSummary,
      recentActivity: recentActivity,
      createdAtLabel: createdAtLabel,
      lastActiveLabel: lastActiveLabel,
      attendanceRate: attendanceRate,
      engagementRate: engagementRate,
      permissionCoverage: totalPermissions == 0
          ? 0
          : (enabledPermissions / totalPermissions) * 100,
      subjectsAssigned: subjects.length,
      lecturesUploaded: lecturesUploaded,
      tasksCreated: tasksCreated,
      postsCreated: postsCreated,
      uploadsCount: uploadsCount,
      scheduleUpdates: scheduleUpdates,
      subjects: subjects,
      permissionGroups: permissionGroups,
      timeline: timeline,
      attendanceTrend: attendanceTrend,
      engagementTrend: engagementTrend,
    );
  }

  List<StaffPermissionGroup> _permissionGroups({
    bool canCreateLectures = true,
    bool canUploadLectureFiles = true,
    bool canManageSections = true,
    bool canUploadTasks = true,
    bool canSetTaskDates = true,
    bool canViewStudentProgress = false,
    bool canPostInCommunity = true,
    bool canModeratePosts = true,
    bool canManageSubjectContent = false,
    bool canUpdateSchedule = false,
    bool canUploadMaterials = true,
    bool canAcademicInteract = true,
  }) {
    return [
      StaffPermissionGroup(
        id: 'content',
        title: 'Content delivery',
        subtitle: 'Lectures, sections, files, and structured academic content.',
        icon: Icons.play_lesson_outlined,
        permissions: [
          StaffPermission(
            id: 'create_lectures',
            title: 'Create lectures',
            description:
                'Publish lecture entries and structure class delivery.',
            enabled: canCreateLectures,
          ),
          StaffPermission(
            id: 'upload_lecture_files',
            title: 'Upload lecture files',
            description: 'Attach slides, recordings, and lecture materials.',
            enabled: canUploadLectureFiles,
          ),
          StaffPermission(
            id: 'manage_sections',
            title: 'Create sections',
            description:
                'Open section sessions and keep related content updated.',
            enabled: canManageSections,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'assessment',
        title: 'Assessment and student follow-up',
        subtitle: 'Tasks, due dates, and student academic visibility.',
        icon: Icons.assignment_turned_in_outlined,
        permissions: [
          StaffPermission(
            id: 'upload_tasks',
            title: 'Upload tasks',
            description: 'Create tasks and attach assessment instructions.',
            enabled: canUploadTasks,
          ),
          StaffPermission(
            id: 'set_due_dates',
            title: 'Add task due dates',
            description: 'Define deadlines and open submission windows.',
            enabled: canSetTaskDates,
          ),
          StaffPermission(
            id: 'view_student_progress',
            title: 'View student progress',
            description:
                'See progress indicators when academic review allows it.',
            enabled: canViewStudentProgress,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'community',
        title: 'Subject community and moderation',
        subtitle:
            'Posts, announcements, and academic interaction with students.',
        icon: Icons.forum_outlined,
        permissions: [
          StaffPermission(
            id: 'post_in_course',
            title: 'Post in course community',
            description:
                'Publish academic notices and answer course questions.',
            enabled: canPostInCommunity,
          ),
          StaffPermission(
            id: 'manage_subject_posts',
            title: 'Manage subject posts',
            description: 'Edit, pin, or moderate subject-related posts.',
            enabled: canModeratePosts,
          ),
          StaffPermission(
            id: 'academic_interaction',
            title: 'Interact with students academically',
            description:
                'Respond to academic questions and follow up on feedback.',
            enabled: canAcademicInteract,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'operations',
        title: 'Subject operations',
        subtitle: 'Materials, schedule control, and content governance.',
        icon: Icons.admin_panel_settings_outlined,
        permissions: [
          StaffPermission(
            id: 'manage_subject_content',
            title: 'Manage subject content',
            description:
                'Edit published materials and subject content structure.',
            enabled: canManageSubjectContent,
          ),
          StaffPermission(
            id: 'update_schedule',
            title: 'Update schedule',
            description: 'Adjust class timing when department approval exists.',
            enabled: canUpdateSchedule,
          ),
          StaffPermission(
            id: 'upload_materials',
            title: 'Upload materials',
            description: 'Add books, sheets, and supplemental academic files.',
            enabled: canUploadMaterials,
          ),
        ],
      ),
    ];
  }

  List<StaffMetricPoint> _metricTrend(List<double> values) {
    const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    return List<StaffMetricPoint>.generate(
      values.length,
      (index) => StaffMetricPoint(
        label: labels[index.clamp(0, labels.length - 1)],
        value: values[index],
      ),
    );
  }

  List<SubjectPermissionCategory> _subjectPermissions({
    required bool allowStudentPosts,
    required bool allowStaffPostModeration,
    required bool summariesVisibleToStudents,
    required bool studentListVisibleToDoctor,
    required bool studentListVisibleToAssistant,
    required bool staffOnlyStudentVisibility,
    required bool lateRegistrationEnabled,
  }) {
    return [
      SubjectPermissionCategory(
        id: 'posts',
        title: 'Posts visibility',
        subtitle: 'Define who opens posts and who monitors the stream.',
        icon: Icons.forum_outlined,
        permissions: [
          SubjectPermissionRule(
            id: 'student_posts',
            title: 'Students can open posts',
            description:
                'When off, students can only read approved staff posts.',
            enabled: allowStudentPosts,
          ),
          SubjectPermissionRule(
            id: 'staff_moderation',
            title: 'Doctor and assistant monitor posts',
            description: 'Assigned staff can review, pin, and moderate posts.',
            enabled: allowStaffPostModeration,
          ),
          const SubjectPermissionRule(
            id: 'admin_monitoring',
            title: 'Admin monitors all post activity',
            description: 'Administrative oversight stays active at all times.',
            enabled: true,
          ),
        ],
      ),
      SubjectPermissionCategory(
        id: 'summaries',
        title: 'Summaries and content access',
        subtitle: 'Control who can view and manage revision material.',
        icon: Icons.summarize_outlined,
        permissions: [
          SubjectPermissionRule(
            id: 'students_view_summaries',
            title: 'Students can access summaries',
            description: 'Published summaries appear inside the subject space.',
            enabled: summariesVisibleToStudents,
          ),
          const SubjectPermissionRule(
            id: 'staff_manage_summaries',
            title: 'Staff can add and manage summaries',
            description:
                'Doctor, assistant, and admin can update summary sets.',
            enabled: true,
          ),
        ],
      ),
      SubjectPermissionCategory(
        id: 'privacy',
        title: 'Student privacy',
        subtitle: 'Keep the enrolled student list staff-only and peer-safe.',
        icon: Icons.lock_outline_rounded,
        permissions: [
          SubjectPermissionRule(
            id: 'doctor_student_list',
            title: 'Doctor can see subject students only',
            description:
                'The doctor sees only students linked to this subject.',
            enabled: studentListVisibleToDoctor,
          ),
          SubjectPermissionRule(
            id: 'assistant_student_list',
            title: 'Assistant can see subject students only',
            description:
                'The assistant sees only the enrolled students for this subject.',
            enabled: studentListVisibleToAssistant,
          ),
          SubjectPermissionRule(
            id: 'staff_only_visibility',
            title: 'Students cannot see each other accounts',
            description:
                'Peer account visibility is blocked and remains staff-only.',
            enabled: staffOnlyStudentVisibility,
          ),
        ],
      ),
      SubjectPermissionCategory(
        id: 'access',
        title: 'Access control',
        subtitle: 'Manage secure entry through code, link, and late joins.',
        icon: Icons.vpn_key_outlined,
        permissions: [
          const SubjectPermissionRule(
            id: 'code_and_link',
            title: 'Access through code and link',
            description: 'Students may enter through either access channel.',
            enabled: true,
          ),
          SubjectPermissionRule(
            id: 'late_registration',
            title: 'Late registration entry',
            description:
                'Late-registered students can join safely without manual staff edits.',
            enabled: lateRegistrationEnabled,
          ),
        ],
      ),
    ];
  }
}
